### ISSUE TITLE
Proposal to rename this repo to blocklist or denylist

### ISSUE THREAD

**Issue by kylerchin** [anudeepND/blacklist#112]
There is a huge problem in tech where Black/White is used to mean allowing or denying. There is also a movement within tech to change this. That's why I'm asking you to change this repo's name as well as instances within composer.json and markdown files. Together, we can make Tech more inclusive.

Thanks,
Kyler

**Comment by spirillen** [comment]
What is excluding by using white/black-list?

Why is the filtering called by these names?

Why should the usage of these 20+ years old names be a `huge problem`?

**Comment by kylerchin** [comment]
@spirillen Just because the names have been engrained into tech, doesn't mean it's right to use segregating names. The truth is that these colours were used in segregating housing, buses, dining areas, churches, queue lines, and all areas of society.  FOr example: Black drinking fountain and white drinking fountain. The terminology carried over to the early days of tech, segregation engrained into the text files of early computing. 

Google's Chrome teams and Android Dev teams have already set a good example by renaming their Black/White lists. https://9to5google.com/2020/06/12/google-android-chrome-blacklist-blocklist-more-inclusive/

**Comment by spirillen** [comment]
These things have nothing to do with each other..... and have whitelist for the light/bright/good, not skin color and the black comes from the darkness/shadows and it also have an religious ref. in the dark and white angels.

In short, the whitelist is representing/synonym for the good in the light and the black is a ref to the darkness where all cats are grey in the night.
There are NON referrals to racismen in these words and the usage hereof. That google and other US companies is switching is done to protecting there goods, YOU, and your newly found political correctness and HARM for something you have been reading on FB.

They switching names to satisfy the masses for whom they successfully have turned into stupid and ignorant brainless zombies who is acknowledge knowledge, but only following the one who shouted the most, to not stand on the outside of the crowd by taking things out of context.

Now you know the real history and references for the wording of the list, know you can help other learning this and put things in the right perspective.

PS: putting links to any google shit is useless, any google is assigned `rcode 3` in my DNS.

**Comment by cyborgspider** [comment]
You're on the wrong side of history here, spirillien. Just change the damn name, the dark angels and white angels won't be offended.

**Comment by markusdresch** [comment]
changing this would alienate many international devs without improving anything. context matters and blacklist does not have to do anything with skin color. if you'd stop to categorize people as "black" or "white", you'd actually do something against racism. changing references to (non-skin) color does not!

**Comment by janw** [comment]
Wow. The folks arguing against this proposal should really check their (to be assumed white) privilege here. [Words matter](https://twitter.com/michaelmontano/status/1278747064701038592), and disregarding inclusionary language as (of all things!) alienating and "not improving anything" is a blatant example of why it is all the more important to raise awareness, and to press for these changes to happen. As @cyborgspider said, you _are_ on the wrong side of history, and it is [already](https://thenextweb.com/dd/2020/07/13/linux-kernel-will-no-longer-use-terms-blacklist-and-slave/) [being](https://www.theverge.com/2020/7/2/21311330/twitter-engineers-master-slave-github-programming-racism) [written](https://bugs.python.org/issue34605), whether you like it or not.

Honestly, it is quite telling that you are offended by and cannot accept a simple change of wording that does not affect your daily lives in any way, while People of Color are constantly confronted with Blackness being assigned negative connotations. Just because "blacklist"/"whitelist" were never consciously intended to be references to skin-color does not make them exist in a world free of social injustice and oppression, and neither does it remove them from the context of institutional racism. As privileged white people and benefactors of that injustice it is our obligation to facilitate change.

And if you cannot be bothered to advocate for that change, at least have some _decency_, would you?

**Comment by markusdresch** [comment]
and it's [being kept as is](https://github.com/openssl/openssl/pull/12089#issuecomment-642297519), whether you like it or not.  you are trying to police internationally established language with no racial connotation whatsoever. and you should work on getting down your perceived high horse and stop sounding so condescending, different people have different opinions.

i give you that: words do matter. so does context. developers should know that. if you think "PoC" when reading "black", you probably should readjust the way you think about people.

**Comment by spirillen** [comment]
Not to mention a couple of hundreds RFC-standards using white/black-list. Are you going to change all of chose two, because somebody is taking things out of contexts? That would simply not make sense.

The best anyone can do, it to enlighten people of what is up and what is down. In this case that was pointed out earlier in this issue.

**Comment by anudeepND** [comment]
Thanks for the inputs on this topic everyone. These names have been in the tech world for a long time. I don't like the idea of comparing it to a particular community. These terms has been industry standard for quite some time.

Also I may need to change the branch `master` to something else. This is not possible because it would break the raw link since the repo doesn't have an alternative mirror. 

Currently there are lots of people using this list. Changing the URL means, the original link will render 404. And it is difficult to inform the users about the change.

**Comment by OmgImAlexis** [comment]
Changing the name wouldn’t cause any issue as the redirect works. Changing the branch would but I’m sure GitHub is going to address that later this year when they add the migration tools in.

**Comment by OmgImAlexis** [comment]
It’s honestly sad that you’re all acting this way. A simple name change wouldn’t harm anyone. You’re kinda acting like a child. 💁‍♀️

**Comment by markusdresch** [comment]
trying to force your opinion on everyone else is childish and asocial behavior. stop trying to police and restrict everyones language and start accepting or at least tolerating other peoples opinions. this issue is completely off topic.

**Comment by spirillen** [comment]
> It’s honestly sad that you’re all acting this way. A simple name change wouldn’t harm anyone. You’re kinda acting like a child. tipping_hand_woman

What is a name change should help??? in the unrelated context you are trying to a chief? nothing!!!

Why is it so hard to accept knowledge over individual words taken out of context?? Is it the fact that the AdWare and tracking business have reached there coal of en-stupid people enough to no longer accept facts?

@OmgImAlexis I'm guessing your next project would be all religion and religious scripts and books like the Koran and Bible, and from your username, well I'm guessing your belongs to the religion who's is behind the biggest slavery business the past couple hundred of years. (This knowledge is called facts)

-------

If you seriously would do any changes, you'll need to open some books and actually read your own history, and then by using the knowledge, know how to work the minds of the few, for whom you disagree with in how the uses a word.

-------
The conclusion for our "intolerance" is simple, we uses the words as they are rightfully referenced from the beginning, and we are eating our own medicine, by trying to teach you the historical meaning.

--------

My best advice to you @OmgImAlexis is simply start accepts and tolerate others, read the history and learn it. In all other way you'll keep banging your head against the wall of knowledge.

As one once said: 
> Our future is written in the history...

**Comment by PatrickDa87** [comment]
Internet was better when 20 years ago...
I'm tired of this woke community which tries to take over every part of our lives. 

@OmgImAlexis : Fork this project and work with the woke community on the allow-list repo. I hope you will find good engineers who work with you voluntarily.

**Comment by arnold-friendly** [comment]
Nothing says "obnoxious", "infuriating" or "cringe inducing", like white people moralizing on behalf of anyone, about anything, because they know what's best. Personally speaking, as someone that grew up in queens, with a boricua (moreno) parent, I would never claim to speak on behalf of anyone else, because people are more complex than what I can cram into a stereotype. More importantly, most people prefer that they speak on their own behalf, because it's just insulting af to think that someone thinks that I am too miserably weak, and stupid, to be subjected to the "black" in "blacklist", day in and out. 

I mean, I didn't get into Science, Tech or Stuyvesant, but I did go to private school and managed to get a CS degree from a strong state school; ok, a state school with a well regarded CS program.  I thought about pursuing a graduate degree from one of the CUNY schools, but I just couldn't face the prospect of having a "masters" in anything! 

Actually, that's not true, I.. just didn't feel like it.  That's a normal reason right? Not insane, like being so distraught over a completely unrelated meaning of a word, that I feel the need to get on a soapbox, to chastise a bunch of strangers. Actually, I am doing it right now, but I am speaking on my behalf, not on behalf of an entire group of people that i've categorized by color. 

In all seriousness, the worst part about this, is that this is a pr stunt, designed to reinforce what exactly? That big tech firms aren't racist? Or evil, or greedy and/or NOT begging for an antitrust suit?  Excuse me, "NOT begging for [additional] antitrust [suits]." 

Anyways, please grow tf up kids - you're embarrassing yourselves and are going to kill us in '22 and '24, because the other side mostly avoids infighting and takes their marching orders with glee.
