### ISSUE TITLE
Domains are not blocked by Pi-hole

### ISSUE THREAD

**Issue by vinothvkr** [anudeepND/blacklist#135]
I have a testing setup at home. Pi-hole -> Pfsense with pfblockerng. Both have adserver.txt setup in list.
I found that below few domains are not being blocked by Pi-hole but blocked by pfblockerng.

- bifrost-api.hotstar.com
- snippets.cdn.mozilla.net
- v10.events.data.microsoft.com
- vortex.data.microsoft.com
- eu1-spiky.wzrkt.com
- cf.hermes.wshareit.com

**Comment by anudeepND** [comment]
@vinothvkr `bifrost-api.hotstar.com` and `cf.hermes.wshareit.com` is already in the list. `v10.events.data.microsoft.com` was removed because it affects XBox Live achievements.

`snippets.cdn.mozilla.net` is not a tracker or advert. It can be turned off in settings - [Mozilla FAQ](https://support.mozilla.org/en-US/kb/snippets-firefox-faq)
