### ISSUE TITLE
Bing blocked

### ISSUE THREAD

**Issue by yegors** [anudeepND/blacklist#22]
The following end up blocking a lot of sites, bing being one of them. 
```
0.0.0.0 a-0001.a-msedge.net
0.0.0.0 a-0002.a-msedge.net
0.0.0.0 a-0003.a-msedge.net
0.0.0.0 a-0004.a-msedge.net
0.0.0.0 a-0005.a-msedge.net
0.0.0.0 a-0006.a-msedge.net
0.0.0.0 a-0007.a-msedge.net
0.0.0.0 a-0008.a-msedge.net
0.0.0.0 a-0009.a-msedge.net
```

```
C:\Users\Test-User>nslookup www.bing.com
Server:  UnKnown
Address:  10.255.255.3

Non-authoritative answer:
Name:    a-0001.a-msedge.net
Address:  0.0.0.0
Aliases:  www.bing.com
          a-0001.a-afdentry.net.trafficmanager.net
```

**Comment by dnmTX** [comment]
@yegors are you sure,cause i'm using @anudeepND's lists as well and the same domains are blocked on my end and i can assure you that `www.bing.com` is opening just fine here.

> The following end up blocking **a lot of sites**, bing being one of them

You mind giving more examples cause so far your claims are unsupported to say the least.

**Comment by yegors** [comment]
They appear in the master branch: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt

**Comment by dnmTX** [comment]
@yegors never mind,i just saw that you're in Canada.
@anudeepND search in StevenBlack's issues for the same problem,from what i can remember Steven is based out of Canada and he was unable to access `bing.com`.Probably the domain in question was the culprit there as well(he ended up removing all the Microsoft's telemetry domains because of it).

**Comment by anudeepND** [comment]
@yegors Is there any other services affected?
