### ISSUE TITLE
Additional innovid domain

### ISSUE THREAD

**Issue by chado99** [anudeepND/blacklist#32]
ag.innovid.com 
Missing from current list of domains. 

 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   cdn.innovid.com
   rtr.innovid.com
   s.innovid.com
   s-static.innovid.com
   dts.innovid.com
   innovid.com
 Match found in http://sysctl.org/cameleon/hosts:
   dts.innovid.com
   rtr.innovid.com
   s-static.innovid.com
   s.innovid.com
 Match found in https://hosts-file.net/ad_servers.txt:
   s.innovid.com
 Match found in http://www.squidblacklist.org/downloads/dg-ads.acl:
   innovid.com
 Match found in https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt:
   frontend5.innovid.com
   frontend6.innovid.com
   frontendqa.innovid.com
   innovid.com
   priority.innovid.com
   tch.innovid.com

**Comment by dnmTX** [comment]
@chado99  off topic here but just to point out.Consider dropping the Cameleon List due to:
After removing all the DEAD Domains and filtering duplicates against StevenBlack's lists you are left with
approximately 7000 (maybe less) domains out of....what...30.000-ish?
Whoever was maintaining that lists is long gone and most of the domains are already added to other lists anyway. This is what i did on my end,didn't even have to think too much.

**Comment by chado99** [comment]
Good tip.

**Comment by anudeepND** [comment]
Thanks @chado99
