### ISSUE TITLE
Google Fonts is blocked

### ISSUE THREAD

**Issue by hectorm** [anudeepND/blacklist#57]
I don't know if this is intentional, but the domain `googleadapis.l.google.com` was added in 62b873ddbd7170ae1c6964186eec0a0d984ab7ef and is causing the problem, since `fonts.googleapis.com` contains a CNAME record to this domain.

**Comment by hectorm** [comment]
Code snippets generated at [fonts.google.com](https://fonts.google.com/) use the domain `fonts.googleapis.com`.

![](https://user-images.githubusercontent.com/852266/63804355-46c11300-c917-11e9-8540-dae9c8ebf7f0.png)

With `dig` we can see how `fonts.googleapis.com` has a CNAME record with value `googleadapis.l.google.com`.

```
$ dig fonts.googleapis.com @1.1.1.1

; <<>> DiG 9.11.3-1ubuntu1.8-Ubuntu <<>> fonts.googleapis.com @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5103
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;fonts.googleapis.com.		IN	A

;; ANSWER SECTION:
fonts.googleapis.com.	901	IN	CNAME	googleadapis.l.google.com.
googleadapis.l.google.com. 216	IN	A	172.217.17.10

;; Query time: 9 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Aug 27 22:05:59 CEST 2019
;; MSG SIZE  rcvd: 101
```

Other blocklists have already erroneously blocked Google Fonts in the past (https://github.com/StevenBlack/hosts/issues/505, https://github.com/AdguardTeam/AdGuardHome/issues/460).

**Comment by hectorm** [comment]
Reproducing the problem depends on how you are using this blocklist.

When you use the `/etc/hosts` file this problem does not occur, but when you implement a DNS block, such as using [Knot Resolver with static hints](https://knot-resolver.readthedocs.io/en/stable/modules.html#static-hints) (e.g., `hints['googleadapis.l.google.com'] = '0.0.0.0'`), any client using this resolver will get the following answer:

```
$ dig fonts.googleapis.com @127.0.0.153

; <<>> DiG 9.11.3-1ubuntu1.8-Ubuntu <<>> fonts.googleapis.com @127.0.0.153
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30148
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;fonts.googleapis.com.		IN	A

;; ANSWER SECTION:
fonts.googleapis.com.	362	IN	CNAME	googleadapis.l.google.com.
googleadapis.l.google.com. 5	IN	A	0.0.0.0

;; Query time: 0 msec
;; SERVER: 127.0.0.153#53(127.0.0.153)
;; WHEN: Wed Aug 28 00:15:00 CEST 2019
;; MSG SIZE  rcvd: 101
```

You can reproduce the problem in any environment that uses **this specific setup**.

**Comment by anudeepND** [comment]
@hectorm Interesting.... Google Fonts works for me when using pi-hole. But I don't know what is delivered over `googleadapis.l.google.com`, it was in my pi-hole log. 
It is better to remove it from the list, what do you think @dnmTX 
I don't want to be too aggressive with the list

**Comment by hectorm** [comment]
This behavior is common in DNS resolvers. For example [systemd-resolved](https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html), the resolver included by default in most distributions that use systemd, behaves in the same way when there is an entry of this type in the `/etc/hosts` file.

**Comment by anudeepND** [comment]
I will keep the domain in the list, I will remove it if I get more reports on this domain. Thanks @hectorm and @dnmTX

**Comment by DRSDavidSoft** [comment]
@hectorm I can confirm the same behavior in [Unbound](https://nlnetlabs.nl/projects/unbound/about/), another DNS resolver and cache server that I use in my setup (**DNScrypt + Unbound**).

@anudeepND I also think that `googleadapis.l.google.com` should not be in the `adservers.txt` list, since it's a general domain and is not exclusively used to serve ads.

Personally I have the `googleadapis.l.google.com` entry in my whitelist, since I've had other issues with that domain being blocked, other than as a CNAME to something like `fonts.google.com`.

I highly encourage you to remove any domains that _is not exclusively used to serve ads_, or _used only to track users_. If a domain (or its CNAME) is known to serve useful content, it should not be blocked.

---

On a sidenote, if anyone's wondering why I block CNAMEs to a blocked domain:
1. Consider an obvious domain like `ads.some-evil-corp.com` that anyone knows about, and block it in their hosts list.
2. When a user's browser tries to connect to that particular domain, the request fails because the domain name exists in their blacklist.
3. Either the person who runs the website, or guys behind `some-evil-corp.com`, register a new domain like: `files.innocent-name.com`.
4. Now, since the new domain is _not_ in the user's blacklist, when the browser tries to make a request, it succeeds and the ads are displayed!

I also block _all_ wildcards, in addition to CNAMEs.  So, if `some-ads-server.com` is blocked, all requests to the following will be blocked as well:
```
s1.some-ads-server.com
s2.some-ads-server.com
....
s9999.some-ads-server.com
```
and so on.

**Comment by anudeepND** [comment]
@DRSDavidSoft Thanks for your valuable info, currently no ads are being served from this domain. I will remove it the next update

**Comment by anudeepND** [comment]
@DRSDavidSoft Thanks for your valuable info, currently no ads are being served from this domain. I will remove it the next update
