### ISSUE TITLE
Consider filtering this list through dead-hosts

### ISSUE THREAD

**Issue by ajayramaswamy** [anudeepND/blacklist#83]
There is a project to do verification and validation of ad block lists at https://github.com/dead-hosts 

I ran this list through that program and it reported more than 4000 entries as invalid / inactive

Be warned that it takes more than 24 hours to complete with 38000+ entries

**Comment by dnmTX** [comment]
@ajayramaswamy  the same developer has newer project and @anudeepND's list is included there:
https://github.com/Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server

The importance here is that the original list must remain untouched,so to be fetched and filtered properly because the so called dead/invalid domains,some of them return back to life and continuing spreading ads and what not.

**Comment by anudeepND** [comment]
@ajayramaswamy I'm aware that this list contains several dead hosts. There are some malware domains that only targets several countries so it is hard to verify that those domains are active or not.

 As @dnmTX said, good guys at Ultimate Hosts Blacklist  maintain a filtered list which periodically runs and filters out invalid and dead domains. If you are using this list with pi-hole any DNS based adblockers, you will not going to face any issues because the devices (like pi zero) can crunch through millions of domains without any hiccups
