### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by scafroglia93** [anudeepND/blacklist#95]
If you need it, I made a diff with a well-kept whitelist

Whitelist ->
https://github.com/notracking/hosts-blocklists-scripts/blob/master/hostnames.whitelist.txt

Diff ->
graph.instagram.com
s0.2mdn.net
manifest.auditude.com
cdns.gigya.com
v10.vortex-win.data.microsoft.com
bestfwdservice.com
v10.events.data.microsoft.com
schibsted.io
vidible.tv
etl.tindersparks.com
seccdn-gl.imrworldwide.com
loggly.com
c.evidon.com
s.zkcdn.net
s.click.aliexpress.com
v20.vortex-win.data.microsoft.com
assets.adobedtm.com
cdn-gl.imrworldwide.com
yui.yahooapis.com

Cheers

**Comment by scafroglia93** [comment]
It's all ok ?

**Comment by anudeepND** [comment]
I will make the changes tomorrow. Thanks for the info

**Comment by scafroglia93** [comment]
ok

**Comment by scafroglia93** [comment]
Wait for your info

**Comment by anudeepND** [comment]
@scafroglia93 Sorry for the late response. I can't remove any without looking why it was blocked in the first place. 

Removed domains:
assets.adobedtm.com (even though it is a tracker it has affected many people)
etl.tindersparks.com
loggly.com
vidible.tv

**Comment by anudeepND** [comment]
@scafroglia93 Sorry for the late response. I can't remove any without looking why it was blocked in the first place.

**Removed domains:**
           
assets.adobedtm.com (even though it is a tracker it has affected many people)
etl.tindersparks.com
loggly.com
vidible.tv
yui.yahooapis.com

**Domain that remains blocked:**
1. ` s0.2mdn.net`  
It is a well known [tracker](https://better.fyi/trackers/2mdn.net/) by DoubleClick. Since it also breaks video streams on couple of sites, I have added it to the [wiki.](https://github.com/anudeepND/blacklist/wiki/Whitelist-Guide)
             
2. `manifest.auditude.com`
The Adobe® Auditude® platform is used by companies that want to provide relevant content and advertisements in videos you watch on the web. Categorized under Advertising, Location, Identity, Tracking. [info](https://github.com/YalePrivacyLab/tracker-profiles/blob/master/trackers/Auditude.md)
                     
3. `cdns.gigya.com` and `v10.vortex-win.data.microsoft.com`
Already addressed in the wiki.
                    
4. `bestfwdservice.com`
Looks like an adware. It redirects to other sketchy sites. Example URL: hxxp://bestfwdservice.com/rg-clkrdr.php?_u=http%3A%2F%2Fnnm1hub.xyz/400&_gvw=zFbGzFtTtGtzGZzFEbG&_typ=1

5. `schibsted.io` 
Known tracker. [info 1](https://sdk.pulse.schibsted.com/#tracking-guide) and [info 2](https://whotracks.me/trackers/schibsted.html)

6. `seccdn-gl.imrworldwide.com` and `cdn-gl.imrworldwide.com`
This domain does not affect Twitch client. You need to whitelist s.amazon-adsystem.com in order to make it work. Mentioned in the wiki.

7. `s.zkcdn.net`
Known [adserver](https://dev.adzerk.com/docs/modifying-the-ad-code). May affect DirecTV Now so I mentioned it in the wiki.

**Need more insights:**
`s.click.aliexpress.com`
